// AUTO-GENERATED by build_smart_env_config.js. DO NOT EDIT.
import smart_actions from './src/collections/smart_actions.js';
import smart_chat_threads from './src/collections/smart_chat_threads.js';
import smart_completions from './src/collections/smart_completions.js';
import smart_contexts from './src/collections/smart_contexts.js';
import { SmartAction } from './src/items/smart_action.js';
import { SmartChatThread } from './src/items/smart_chat_thread.js';
import { render as chat_component } from './src/components/chat.js';
import { render as chat_context_builder_component } from './src/components/chat_context_builder.js';
import { render as chat_model_settings_component } from './src/components/chat_model_settings.js';
import { render as chat_thread_settings_component } from './src/components/chat_thread_settings.js';
import { render as completion_component } from './src/components/completion.js';
import { render as confirm_delete_component } from './src/components/confirm_delete.js';
import { render as message_action_component } from './src/components/message_action.js';
import { render as message_assistant_component } from './src/components/message_assistant.js';
import { render as message_model_info_component } from './src/components/message_model_info.js';
import { render as message_system_component } from './src/components/message_system.js';
import { render as message_user_component } from './src/components/message_user.js';
import { render as overlay_requires_settings_component } from './src/components/overlay_requires_settings.js';
import { render as thread_component } from './src/components/thread.js';

export const smart_env_config = {
  collections: {
    smart_actions,
    smart_chat_threads,
    smart_completions,
    smart_contexts
  },
  item_types: {
    SmartAction,
    SmartChatThread
  },
  components: {
    chat: chat_component,
    chat_context_builder: chat_context_builder_component,
    chat_model_settings: chat_model_settings_component,
    chat_thread_settings: chat_thread_settings_component,
    completion: completion_component,
    confirm_delete: confirm_delete_component,
    message_action: message_action_component,
    message_assistant: message_assistant_component,
    message_model_info: message_model_info_component,
    message_system: message_system_component,
    message_user: message_user_component,
    overlay_requires_settings: overlay_requires_settings_component,
    thread: thread_component
  }
};
